import React, { ReactElement } from 'react';
import { TextStyle, ViewStyle, TextInputProps } from 'react-native';
import { PropsOfIcon } from '../Icon';
declare type Props = TextInputProps & {
    inputStyle?: TextStyle | ViewStyle;
    style?: TextStyle | ViewStyle;
    mainContainerStyle?: ViewStyle;
    leftIcon?: PropsOfIcon;
    rightAction?: ReactElement;
    rightActionButtonStyle?: ViewStyle;
    inputContainerStyle?: ViewStyle;
    onRightIconPress?: () => void;
    title?: string;
    allowFontScaling?: boolean;
    titleStyle?: TextStyle;
    value?: string;
    onChnageText?: (text: string) => void;
};
declare const AppTextInput: React.FC<Props>;
export default AppTextInput;
