import React, { ReactElement } from 'react';
import { TextInputProps, ViewStyle, TextStyle, ColorValue } from 'react-native';
declare type Props = TextInputProps & {
    placeholder?: string;
    borderWidth?: number;
    activeBorderColor?: ColorValue;
    inactiveBorderColor?: ColorValue;
    containerStyle?: ViewStyle;
    placeholderTextStyle?: TextStyle;
    placeholderTextColor?: ColorValue;
    rightAction?: ReactElement;
    rightActionButtonStyle?: ViewStyle;
    onRightIconPress?: () => void;
    value?: string;
    onChangeText?: (value: string) => void;
    inputStyle?: TextStyle | ViewStyle;
    inputHeight?: number;
    backgroundColor?: ColorValue;
    placeholderTextSize?: number;
    style?: TextStyle | ViewStyle;
};
declare const AppTextInputOutlined: React.FC<Props>;
export default AppTextInputOutlined;
