import React, { ReactElement } from 'react';
import { ColorValue, TextStyle, ViewStyle } from 'react-native';
import { PropsOfIcon } from '../Icon';
declare type Props = {
    inputStyle?: ViewStyle;
    borderWidth?: number;
    inputTextStyle?: TextStyle;
    selectedValue: string;
    activeBorderColor?: ColorValue;
    inactiveBorderColor?: ColorValue;
    placeholder?: string;
    placeholderColor?: ColorValue;
    options: Array<any>;
    valueKey?: string;
    labelKey?: string;
    backdropColor?: ColorValue;
    backdropOpacity?: number;
    placeholderTextStyle?: TextStyle;
    backdrop?: boolean;
    containerStyle?: ViewStyle;
    modalContainerStyle?: ViewStyle;
    modalBackgroundColor?: ColorValue;
    backgroundColor?: ColorValue;
    renderItem: (item: any, index: number, onPress: () => void, isSelected: boolean) => ReactElement;
    closeIcon?: PropsOfIcon;
    modalHeading?: string;
    modalHeadingTitleStyle?: TextStyle;
    placeholderTextSize?: number;
    modalHeaderShadow?: boolean;
    inputHeight?: number;
    showHeader?: boolean;
    onValueSelect?: (selectedValue: any) => void;
    inputRightIcon?: PropsOfIcon;
};
declare const PickerComponentOutlined: React.FC<Props>;
export default PickerComponentOutlined;
