import React from 'react';
import { ColorValue, ViewStyle, TextStyle, ImageSourcePropType, ImageStyle } from 'react-native';
import { PropsOfIcon } from '../Icon';
declare type RightActionProps = {
    icon?: React.ReactNode;
    onPress?: () => void;
};
declare type Props = {
    title?: string;
    titlePosition?: 'middle' | 'left';
    leftComponent?: 'image' | 'icon';
    leftImage?: ImageSourcePropType;
    leftIcon?: PropsOfIcon;
    leftImageStyle?: ImageStyle;
    backgroundColor?: ColorValue;
    style?: ViewStyle;
    barStyle?: 'dark-content' | 'light-content';
    titleStyle?: TextStyle | ViewStyle;
    titleType?: 'image' | 'text';
    titleImage?: ImageSourcePropType;
    titleImageStyle?: ImageStyle;
    rightActions?: RightActionProps[];
    shadow?: boolean;
    statusBarHidden?: boolean;
    statusBarTranslucent?: boolean;
    subTitle?: string;
    subTitleStyle?: TextStyle;
    onLeftButtonPress?: () => void;
    rightActionContainerStyle?: ViewStyle;
};
declare const MainAppBar: React.FC<Props>;
export default MainAppBar;
